function [] = print_schedule_pLOG_pS4ER...
    (max_instances, res_name, res_instances_usage)
% function [] = print_schedule_pLOG_pS4ER...
%       (max_instances, res_name, res_instances_usage)
% print_schedule_pLOG_print_summary_for_each_resource


if eq(max_instances, 1)
    disp(['Resource Instance: ',res_name,':: Used ',...
        int2str(res_instances_usage(1,1)),' times. ', ...
        'Utilization time: ', int2str(res_instances_usage(2,1))]);
else
    for j = 1:max_instances
        disp(['Resource Instance: (', res_name, '-', ...
            int2str(j),  '):: Used ',...
            int2str(res_instances_usage(1,j)), ' times.  ', ...
            'Utilization time: ', int2str(res_instances_usage(2,j))]);
    end
end